### ISSUE TITLE
Boundaries do not work

### ISSUE THREAD

**Issue by musicformellons** [hkrishna/mapboxgl-vector-tiles#3]
@hkrishna Both the boundaries for countries and for states do not appear on the map?

**Comment by hkrishna** [comment]
hey @musicformellons please look at https://github.com/mapzen/mapboxgl-vector-tiles because thats more updated and maintained version of this. I need to update this repo as soon as I find some time.

**Comment by musicformellons** [comment]
Got it working using latest versions.
